### ISSUE TITLE
Question about link prediction

### ISSUE THREAD

**Issue by LLMforScience** [VITA-Group/LLaGA#2]
Hi, 

I find that there maybe data leakage of link predicion experiments. 

As shown in the following example, the test  link is [35140, 42213], but this test edge has been leaked in your input neighbor information.

<img width="1521" alt="image" src="https://github.com/VITA-Group/LLaGA/assets/83741666/ab55f3a9-9e3c-4576-881c-7f2d7f07ca48">

**Comment by ChenRunjin** [comment]
Since the four datasets are not officially designated for link prediction tasks, we adopt the approach used by GraphGPT for conducting link prediction.  
GraphGPT does not exclude test links from their graphs, aligning with a transductive setting. Our GNN baselines similarly employ this transductive approach for consistency.

**Comment by ChenRunjin** [comment]
Removing the test link might be a better experimental design. We may consider adding this kind of setting  in the future. 
Currently, to allow you to experience the results under this setting on LLaGA, you can ad hoc remove the src or dst nodes on the template if they appear in  the other sequence for ND template during testing. 
I just did a simple test on the cora dataset and classification expert projector and found that the accuracy still reached 0.97+. You can also try it on other datasets.

**Comment by tjb-tech** [comment]
> unreasonable

Hi, I am one of authors of GraphGPT. Actually, we have discussed this question before releasing GraphGPT. And finally, we follow the most common settings in the graph learning domain, an example of processing link prediction data could be found in https://colab.research.google.com/drive/1xpzn1Nvai1ygd_P5Yambc_oe4VBPK_ZT?usp=sharing (Official tutorial of PyG).

**Comment by ChenRunjin** [comment]
I just recheck the Link prediction data of GraphGPT, it seems to be my fault, I just found node1 appears in the graph of node2, but ignore that it may be 2-hop neighbor, so I  misunderstand their settings.  Very sorry about that.
I will redo my link prediction experiments systematically as soon as possible (get several main results before the end of next week) and update the results to you.
Before getting the results, you can following the simple setting I mentioned before,  remove the link just in test stage. I test this setting on cora dataset and found the results do not change too much.

**Comment by ChenRunjin** [comment]
Hi all,
I re-evaluated LLaGA under the new link prediction setting. In this setting, we exclude the test link prior to neighbor sampling. I conducted tests on LLaGA in both the classification expert and task expert setting to assess its versatility, as well as in a zero-shot setting to examine its generalizability. The key findings are as follows:

1. In this new setting, LLaGA continues to demonstrate superior versatility and generalizability when compared to baseline models.
2.  LLaGA  outperforms baselines even more compared with the original setting on zero-shot tasks . This is likely because baseline models struggle to adapt to unseen data within this new setting.
<img width="1257" alt="image" src="https://github.com/VITA-Group/LLaGA/assets/44256049/ff935b5b-5226-4813-90e6-fd8dd2941a33">

Overall,  the outcomes are consistent with those observed in the original setting. On smaller datasets, both baseline and LLaGA performance may experience a slight decline. This can be attributed to the potential scarcity of node neighbors in smaller datasets. Removing these links along with their 2-hop neighbors, tends to have a more pronounced impact. (Different from the naive method I previously said, which involved replacing the node in the sequence with [PAD]. Instead, here we eliminate the node along with the 2-hop neighbors it introduces)

Thank you all for the discussion which make LLaGA better!

**Comment by ChenRunjin** [comment]
Yes, I will update  arXiv as soon as possible after I finished re-evaluating all experiments related to link prediction task.

**Comment by ChenRunjin** [comment]
Firstly, you are training in a single focus setting, while 91.2 is the task expert setting (but I  think you may also get a result close to 91.2 in this setting).
Secondly, you may be using the first version of my code,  which contains an error in the eval_lp  function in eval_res.py due to a typo made during code formatting.  I have fixed it several days ago, please pull the newest master. (don't worry, you don't need to re evaluate, just change the function for computing metrics)

**Comment by SwaggyZhang** [comment]
> Since the four datasets are not officially designated for link prediction tasks, we adopt the approach used by GraphGPT for conducting link prediction. GraphGPT does not exclude test links from their graphs, aligning with a transductive setting. This design does not constitute data leakage since test answers are not exposed to the model during training, although it potentially simplifies the task. Since link prediction on these datasets is not widely practiced, it may be challenging to find directly comparable results in existing literature. To ensure fairness and consistency in our evaluation, all of our GNN baselines adopt this same transductive setting.

Hello Runjin,

I have reproduced the generation of jsonl files, and get the same format as yours. However, the numbers of link prediction samples in both train and test files are different from yours.

Could you please tell me your method to split the datasets such as pubmed?
